### Importing numpy

In [1]:
import numpy as np

### Checking numpy version

In [2]:
print(np.__version__)

1.24.1


### Creating arrays using numpy
 - The array object in NumPy is called **ndarray**.
 - We can create a NumPy ndarray object by using the array() function.
 - we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in array:
 - 0-D arrays (also called scalars)
 - 1-D arrays
 - 2-D arrays (mostly used)
    - NumPy has a whole sub module dedicated towards matrix operations called **numpy.mat**
 - 3-D arrays
 - multidimensional arrays

In [5]:
arr = np.array(42)
print("0-D arrays")
print(arr)
print("------------------------")
arr = np.array([1, 2, 3, 4, 5])
print("1-D arrays")
print(arr)
print("------------------------")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("2-D arrays")
print(arr)
print("------------------------")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("3-D arrays")
print(arr)
print("------------------------")

0-D arrays
42
------------------------
1-D arrays
[1 2 3 4 5]
------------------------
2-D arrays
[[1 2 3]
 [4 5 6]]
------------------------
3-D arrays
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
------------------------


### Check number of dimensions:
- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
